name: Continuous Integration

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0,7 * * *'

jobs:
  test:
    strategy:
      matrix:
        java: [8, 11]
    name: Java${{ matrix.java }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.${{ matrix.java }}
      - uses: coursier/cache-action@v5
      - name: Run tests
        run: sbt test
